# Generated by Django 4.1.3 on 2022-11-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('duration', models.FloatField(default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.director')),
            ],
        ),
    ]
